"""Gera charadas.json e respostas.json com 150 itens."""
import json
from pathlib import Path

DADOS = [
    ("Tenho cidades, mas não casas. Tenho montanhas, mas não pedras. Tenho rios, mas não água. O que sou eu?",
     ["Representa lugares do mundo real.", "Pode ser dobrado e guardado na mochila.", "Geógrafos e viajantes usam muito."], "mapa"),
    ("Quanto mais você tira de mim, mais forte eu fico. O que sou eu?",
     ["Feita de elos metálicos.", "Usada para prender ou segurar.", "Quanto mais unida, mais resistente."], "cadeia"),
    ("Ando sem pernas, entro sem bater e saio sem ser convidado. O que sou eu?",
     ["Sopra entre as dunas do deserto.", "Move folhas e bandeiras.", "Não se vê, mas se sente."], "vento"),
    ("Tenho chaves, mas não abro portas. Tenho espaço, mas não quartos. O que sou eu?",
     ["Usado para digitar mensagens.", "Possui letras e símbolos.", "Conectado ao computador."], "teclado"),
    ("Quanto mais seco fico, mais molhado fico. O que sou eu?",
     ["Usado para limpar o rosto.", "Absorve líquidos.", "Fica em banheiros e cozinhas."], "toalha"),
    ("Tenho cabeça e cauda, mas não tenho corpo. O que sou eu?",
     ["Usada para pagar e receber.", "Feita de metal.", "Cai no chão e faz barulho."], "moeda"),
    ("Quanto mais você tira, mais eu peso. O que sou eu?",
     ["Fica no chão do mar.", "Tem buracos por onde a água passa.", "Pescadores usam para pegar peixes."], "rede"),
    ("Nasci grande e morri pequeno. O que sou eu?",
     ["Usada em festas e aniversários.", "Tem um pavio que se acende.", "Derrete conforme queima."], "vela"),
    ("Tenho olhos, mas não vejo. Tenho boca, mas não falo. O que sou eu?",
     ["Usado para costurar roupas.", "Tem furo pequeno na ponta.", "Passa linha por dentro."], "agulha"),
    ("Quanto mais velho fico, mais valioso me torno. O que sou eu?",
     ["Guardado em garrafas especiais.", "Feito de uvas fermentadas.", "Melhora com o tempo."], "vinho"),
    ("Tenho dentes, mas não mordo. O que sou eu?",
     ["Usado para pentear cabelos.", "Tem dentes finos e regulares.", "Encontra-se em banheiros."], "pente"),
    ("Quanto mais você me usa, mais fino eu fico. O que sou eu?",
     ["Usado para escrever e desenhar.", "Tem grafite no centro.", "Aponta-se quando fica curto."], "lapis"),
    ("Tenho pés, mas não ando. Tenho braços, mas não abraço. O que sou eu?",
     ["Usada para sentar e descansar.", "Tem quatro pernas.", "Fica em salas e cozinhas."], "cadeira"),
    ("Quanto mais alto sobe, mais fino fica. O que sou eu?",
     ["Sai da chaleira quente.", "Visível no ar frio.", "Desaparece no céu."], "fumaca"),
    ("Tenho asas, mas não voo. Tenho cauda, mas não sou animal. O que sou eu?",
     ["Usado para enviar cartas.", "Cola-se no verso do envelope.", "Tem valor para correios."], "selo"),
    ("Quanto mais você me enche, mais leve eu fico. O que sou eu?",
     ["Usado em festas e balões.", "Enche-se com ar ou gás.", "Flutua quando cheio."], "balao"),
    ("Tenho rosto, mas não tenho corpo. Tenho mãos, mas não tenho braços. O que sou eu?",
     ["Marca as horas do dia.", "Tem ponteiros que giram.", "Fica na parede ou pulso."], "relogio"),
    ("Quanto mais escuro fica o céu, mais brilhante eu fico. O que sou eu?",
     ["Aparece à noite no céu.", "Guia viajantes no deserto.", "Brilha distante e fixo."], "estrela"),
    ("Tenho folhas, mas não sou árvore. Tenho capa, mas não sou livro. O que sou eu?",
     ["Usado para anotar receitas.", "Tem páginas em branco.", "Guarda ideias e lembretes."], "caderno"),
    ("Quanto mais você me corta, mais eu cresço. O que sou eu?",
     ["Cresce no topo da cabeça.", "Vai ao cabeleireiro.", "Pode ser longo ou curto."], "cabelo"),
    ("Tenho pescoço, mas não tenho cabeça. O que sou eu?",
     ["Usada para servir vinho.", "Feita de vidro ou cerâmica.", "Tem formato elegante."], "garrafa"),
    ("Quanto mais você me guarda, mais eu sumo. O que sou eu?",
     ["Aparece em vidros e espelhos.", "Forma-se com calor e umidade.", "Some quando o ar esquenta."], "orvalho"),
    ("Tenho agulha, mas não costuro. Tenho números, mas não conto. O que sou eu?",
     ["Usado para medir temperatura.", "Mostra se está quente ou frio.", "Tem mercúrio ou álcool dentro."], "termometro"),
    ("Quanto mais você me esconde, mais eu apareço. O que sou eu?",
     ["Aparece no rosto envergonhado.", "Deixa as bochechas vermelhas.", "Sinal de timidez."], "rubor"),
    ("Tenho coroa, mas não sou rei. Tenho raiz, mas não sou planta. O que sou eu?",
     ["Usado para proteger a cabeça do sol.", "Tem aba na frente.", "Usado em praias e campos."], "chapeu"),
    ("Quanto mais você me quebra, mais eu brilho. O que sou eu?",
     ["Formado por gotas de chuva e sol.", "Tem cores no céu.", "Aparece após a tempestade."], "arco iris"),
    ("Tenho barba, mas não sou homem. Tenho olhos, mas não vejo. O que sou eu?",
     ["Cresce no campo e pomar.", "Vermelho e doce por dentro.", "Usado em saladas e sucos."], "morango"),
    ("Quanto mais você me aperta, mais eu escorrego. O que sou eu?",
     ["Usado para untar pães.", "Feito de leite ou plantas.", "Derrete com calor."], "manteiga"),
    ("Tenho escamas, mas não sou peixe. Tenho asas, mas não voo. O que sou eu?",
     ["Cresce em árvores tropicais.", "Amarelo por fora, branco por dentro.", "Fruta doce e curva."], "banana"),
    ("Quanto mais você me olha, mais eu desapareço. O que sou eu?",
     ["Aparece quando você dorme.", "Pode ser doce ou assustador.", "Some ao acordar."], "sonho"),
    ("Tenho boca, mas não falo. Tenho dentes, mas não mastigo. O que sou eu?",
     ["Usado para abrir cartas.", "Tem lâmina afiada.", "Corta papel facilmente."], "tesoura"),
    ("Quanto mais chove, mais eu cresço. O que sou eu?",
     ["Forma-se no céu escuro.", "Pode ser branca ou cinza.", "Traz chuva consigo."], "nuvem"),
    ("Tenho pernas, mas não ando. Tenho costas, mas não sinto dor. O que sou eu?",
     ["Usada para sentar à mesa.", "Tem quatro pernas de madeira.", "Acompanha mesas de jantar."], "cadeira"),
    ("Quanto mais você me esfrega, mais eu brilho. O que sou eu?",
     ["Usado para limpar metais.", "Remove manchas e ferrugem.", "Deixa superfícies reluzentes."], "esponja"),
    ("Tenho olhos, mas não choro. Tenho agulha, mas não costuro. O que sou eu?",
     ["Usado para furar papel.", "Deixa marcas pequenas.", "Fica sobre mesas de escritório."], "alfinete"),
    ("Quanto mais você me aquece, mais eu derreto. O que sou eu?",
     ["Usado em velas e castiçais.", "Feito de cera colorida.", "Ilumina ambientes escuros."], "vela"),
    ("Tenho folhas, mas não caio no outono. O que sou eu?",
     ["Usado para ler histórias.", "Tem capa dura ou mole.", "Guarda conhecimento."], "livro"),
    ("Quanto mais você me puxa, mais eu resisto. O que sou eu?",
     ["Usado para prender roupas.", "Tem mola forte.", "Segura papéis juntos."], "clip"),
    ("Tenho roda, mas não sou carro. Tenho corrente, mas não sou cadeia. O que sou eu?",
     ["Usada para pedalar na rua.", "Tem guidão e selim.", "Transporte ecológico."], "bicicleta"),
    ("Quanto mais você me seca, mais eu racho. O que sou eu?",
     ["Cresce em campos e jardins.", "Vermelho por fora e dentro.", "Usado em molhos e saladas."], "tomate"),
    ("Tenho cauda, mas não sou animal. Tenho luz, mas não sou sol. O que sou eu?",
     ["Usada para iluminar escadas.", "Acende-se com fósforo.", "Protege a chama do vento."], "lanterna"),
    ("Quanto mais você me vira, mais eu giro. O que sou eu?",
     ["Usado para abrir parafusos.", "Tem cabo e ponta metálica.", "Ferramenta de mecânico."], "chave"),
    ("Tenho asas, mas não sou pássaro. Tenho motor, mas não falo. O que sou eu?",
     ["Voa pelo céu azul.", "Transporta passageiros.", "Tem turbinas potentes."], "aviao"),
    ("Quanto mais você me enche, mais pesado eu fico. O que sou eu?",
     ["Usado para carregar água.", "Feito de plástico ou metal.", "Leva-se na mochila."], "cantil"),
    ("Tenho lâmina, mas não corto carne. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usada para cortar grama.", "Tem cabo longo.", "Cuida do jardim."], "enxada"),
    ("Quanto mais você me bate, mais eu soo. O que sou eu?",
     ["Usado para bater ovos.", "Tem fios metálicos.", "Mistura ingredientes."], "batedor"),
    ("Tenho tela, mas não sou cinema. Tenho teclas, mas não sou piano. O que sou eu?",
     ["Usado para navegar na internet.", "Mostra imagens e textos.", "Fica sobre a mesa."], "monitor"),
    ("Quanto mais você me estica, mais eu volto. O que sou eu?",
     ["Usado para prender cabelo.", "Tem elasticidade.", "Segura o penteado."], "elastico"),
    ("Tenho raiz, mas não sou planta. Tenho corpo, mas não sou humano. O que sou eu?",
     ["Usado para medir distâncias.", "Tem marcações graduadas.", "Estudantes usam na escola."], "regua"),
    ("Quanto mais você me sopra, mais eu apago. O que sou eu?",
     ["Usado em aniversários.", "Brilha sobre o bolo.", "Apaga-se com um sopro."], "vela"),
    ("Tenho lentes, mas não vejo. Tenho hastes, mas não abraço. O que sou eu?",
     ["Usado para corrigir visão.", "Fica sobre o nariz.", "Protege os olhos do sol."], "oculos"),
    ("Quanto mais você me dobra, mais eu ocupo espaço. O que sou eu?",
     ["Usado para guardar roupas.", "Tem zíper ou botões.", "Leva-se em viagens."], "mala"),
    ("Tenho ponta, mas não furo. Tenho tinta, mas não sou quadro. O que sou eu?",
     ["Usado para escrever permanentemente.", "Marca papéis e tecidos.", "Não apaga facilmente."], "caneta"),
    ("Quanto mais você me roda, mais eu afundo. O que sou eu?",
     ["Usado para furar madeira.", "Tem ponta espiral.", "Operado com furadeira."], "broca"),
    ("Tenho tampa, mas não sou panela. Tenho bico, mas não sou pássaro. O que sou eu?",
     ["Usada para servir chá.", "Feita de porcelana.", "Despeja líquido quente."], "bule"),
    ("Quanto mais você me esfrega, mais eu espumo. O que sou eu?",
     ["Usado para lavar pratos.", "Remove gordura.", "Faz espuma na água."], "sabao"),
    ("Tenho corda, mas não sou violão. Tenho gancho, mas não sou pescador. O que sou eu?",
     ["Usado para fechar casacos.", "Sobe e desce.", "Prende duas partes."], "zíper"),
    ("Quanto mais você me aperta, mais eu abro. O que sou eu?",
     ["Usado para prender papéis.", "Tem mola metálica.", "Deixa marcas no papel."], "grampo"),
    ("Tenho hélice, mas não sou ventilador. Tenho casco, mas não sou tartaruga. O que sou eu?",
     ["Navega sobre o mar.", "Transporta carga e pessoas.", "Ancora-se no porto."], "navio"),
    ("Quanto mais você me molha, mais eu inchado fico. O que sou eu?",
     ["Usado para limpar superfícies.", "Absorve água e sujeira.", "Fica na cozinha."], "esponja"),
    ("Tenho teclas pretas e brancas. O que sou eu?",
     ["Usado para tocar melodias.", "Tem pedais embaixo.", "Instrumento clássico."], "piano"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para servir leite.", "Feito de vidro ou plástico.", "Tem bico para despejar."], "jarra"),
    ("Tenho rodas, mas não ando sozinho. Tenho motor, mas não falo. O que sou eu?",
     ["Anda pelas ruas da cidade.", "Transporta famílias.", "Estaciona em garagens."], "carro"),
    ("Quanto mais você me expõe ao sol, mais eu escureço. O que sou eu?",
     ["Usado para proteger a pele.", "Espalha-se no corpo.", "Evita queimaduras."], "protetor"),
    ("Tenho lâmina, mas não corto pão. Tenho cabo, mas não sou martelo. O que sou eu?",
     ["Usada para podar galhos.", "Corta plantas e arbustos.", "Tem lâminas cruzadas."], "tesoura"),
    ("Quanto mais você me enche de ar, mais eu flutuo. O que sou eu?",
     ["Usado em festas infantis.", "Estoura com facilidade.", "Sobe até o teto."], "balao"),
    ("Tenho tela, mas não sou televisão. Tenho botões, mas não sou elevador. O que sou eu?",
     ["Usado para fazer ligações.", "Cabe no bolso.", "Envia mensagens."], "celular"),
    ("Quanto mais você me aquece, mais eu estalo. O que sou eu?",
     ["Usado para fazer pipoca.", "Estoura os grãos.", "Faz barulho na panela."], "milho"),
    ("Tenho cabo, mas não sou espada. Tenho fio, mas não sou linha. O que sou eu?",
     ["Usado para serrar madeira.", "Tem dentes afiados.", "Corta troncos."], "serra"),
    ("Quanto mais você me pisa, mais eu afundo. O que sou eu?",
     ["Forma-se na praia.", "Molda-se com os pés.", "Desmorona com a maré."], "areia"),
    ("Tenho pétalas, mas não sou rosa. Tenho caule, mas não sou árvore. O que sou eu?",
     ["Cresce em jardins coloridos.", "Atrai abelhas e borboletas.", "Presente comum."], "flor"),
    ("Quanto mais você me seca, mais eu quebro. O que sou eu?",
     ["Usado para construir casas.", "Molda-se com água.", "Seca ao sol."], "barro"),
    ("Tenho gavetas, mas não sou armário. Tenho tampo, mas não sou mesa. O que sou eu?",
     ["Usado para guardar documentos.", "Fica no escritório.", "Organiza papéis."], "gaveta"),
    ("Quanto mais você me sacode, mais eu respingo. O que sou eu?",
     ["Usado para regar plantas.", "Tem bico fino.", "Espalha água."], "regador"),
    ("Tenho cordas, mas não sou arco. Tenho som, mas não sou voz. O que sou eu?",
     ["Usado para tocar música.", "Tem seis cordas.", "Instrumento popular."], "violao"),
    ("Quanto mais você me esfrega, mais eu limpo. O que sou eu?",
     ["Usado para lavar o chão.", "Tem cerdas duras.", "Remove sujeira."], "vassoura"),
    ("Tenho lente, mas não sou câmera. Tenho luz, mas não sou lampada. O que sou eu?",
     ["Usado para ampliar textos.", "Aumenta letras pequenas.", "Idosos usam para ler."], "lupa"),
    ("Quanto mais você me aquece, mais eu fervo. O que sou eu?",
     ["Usado para cozinhar massas.", "Ferve água rapidamente.", "Fica sobre o fogão."], "panela"),
    ("Tenho rodas, mas não sou caminhão. Tenho guidão, mas não sou bicicleta. O que sou eu?",
     ["Usado para empurrar bebês.", "Tem cinto de segurança.", "Leva crianças ao parque."], "carrinho"),
    ("Quanto mais você me estica, mais eu fino fico. O que sou eu?",
     ["Usado para amarrar pacotes.", "Resiste a puxões.", "Segura objetos juntos."], "barbante"),
    ("Tenho ponte, mas não sou rio. Tenho lentes, mas não vejo. O que sou eu?",
     ["Usado para cobrir o rosto.", "Protege contra poeira.", "Usado em hospitais."], "mascara"),
    ("Quanto mais você me bate, mais eu cresço. O que sou eu?",
     ["Usado para fazer pão.", "Precisa de fermento.", "Cresce no forno."], "massa"),
    ("Tenho cabo, mas não sou vassoura. Tenho cerdas, mas não sou pincel. O que sou eu?",
     ["Usado para pintar paredes.", "Espalha tinta.", "Deixa marcas coloridas."], "rolo"),
    ("Quanto mais você me inclina, mais eu vazio. O que sou eu?",
     ["Usado para medir líquidos.", "Tem marcações graduadas.", "Laboratórios usam muito."], "proveta"),
    ("Tenho abas, mas não sou caderno. Tenho lâmina, mas não corto. O que sou eu?",
     ["Usado para marcar páginas.", "Fica entre folhas do livro.", "Indica onde parou."], "marca"),
    ("Quanto mais você me aquece, mais eu derreto. O que sou eu?",
     ["Usado para fazer sorvete.", "Congela líquidos.", "Mantém alimentos frios."], "freezer"),
    ("Tenho tela, mas não sou cinema. Tenho controle, mas não mando. O que sou eu?",
     ["Usado para assistir filmes.", "Fica na sala de casa.", "Passa programas e séries."], "televisao"),
    ("Quanto mais você me aperta, mais eu saio. O que sou eu?",
     ["Usado para espremer frutas.", "Extrai suco.", "Fica na cozinha."], "espremedor"),
    ("Tenho lâmina, mas não corto cabelo. Tenho motor, mas não sou carro. O que sou eu?",
     ["Usado para raspar barba.", "Desliza sobre a pele.", "Deixa rosto liso."], "barbeador"),
    ("Quanto mais você me molha, mais eu escorrego. O que sou eu?",
     ["Usado para limpar o chão.", "Espalha-se com pano.", "Remove manchas."], "detergente"),
    ("Tenho tampa, mas não sou pote. Tenho fio, mas não sou linha. O que sou eu?",
     ["Usado para ferver água.", "Desliga sozinho.", "Faz chá e café."], "chaleira"),
    ("Quanto mais você me enche, mais eu explodo. O que sou eu?",
     ["Usado para cozinhar arroz.", "Fecha com tampa.", "Libera vapor."], "panela"),
    ("Tenho lâmpada, mas não ilumino sozinho. Tenho tela, mas não sou cinema. O que sou eu?",
     ["Usado para projetar imagens.", "Passa slides e filmes.", "Apresenta aulas."], "projetor"),
    ("Quanto mais você me esfrega, mais eu brilho. O que sou eu?",
     ["Usado para polir prata.", "Remove oxidação.", "Deixa metais brilhantes."], "polidor"),
    ("Tenho cabo, mas não sou espada. Tenho ponta, mas não furo. O que sou eu?",
     ["Usado para cavar buracos.", "Remove terra.", "Planta mudas."], "pa"),
    ("Quanto mais você me aquece, mais eu cozinho. O que sou eu?",
     ["Usado para assar bolos.", "Fica embutido na cozinha.", "Tem prateleiras internas."], "forno"),
    ("Tenho rodas, mas não ando na rua. Tenho esteira, mas não sou carro. O que sou eu?",
     ["Usado para correr em casa.", "Simula caminhada.", "Fica na academia."], "esteira"),
    ("Quanto mais você me aperta, mais eu marco. O que sou eu?",
     ["Usado para carimbar papéis.", "Deixa impressão colorida.", "Valida documentos."], "carimbo"),
    ("Tenho lâmina, mas não corto grama. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para aparar cerca viva.", "Corta galhos finos.", "Cuida do jardim."], "tesoura"),
    ("Quanto mais você me molha, mais eu inchado fico. O que sou eu?",
     ["Usado para limpar mesas.", "Absorve líquidos derramados.", "Descartável ou reutilizável."], "pano"),
    ("Tenho tela, mas não sou celular. Tenho teclado, mas não digito. O que sou eu?",
     ["Usado para calcular contas.", "Mostra números.", "Estudantes usam na escola."], "calculadora"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para servir sopa.", "Tem cabo longo.", "Mergulha no caldo."], "concha"),
    ("Tenho lâmina, mas não corto papel. Tenho motor, mas não sou ventilador. O que sou eu?",
     ["Usado para cortar grama.", "Passa pelo jardim.", "Deixa o gramado baixo."], "cortador"),
    ("Quanto mais você me aquece, mais eu derreto. O que sou eu?",
     ["Usado para selar envelopes.", "Gruda papéis.", "Derrete com calor."], "cola"),
    ("Tenho cabo, mas não sou martelo. Tenho cerdas, mas não sou vassoura. O que sou eu?",
     ["Usado para pintar quadros.", "Carrega tinta.", "Artistas usam muito."], "pincel"),
    ("Quanto mais você me enche, mais eu pesado fico. O que sou eu?",
     ["Usado para carregar compras.", "Feito de plástico ou papel.", "Leva-se do mercado."], "sacola"),
    ("Tenho tampa, mas não sou panela. Tenho bico, mas não sou bule. O que sou eu?",
     ["Usado para filtrar café.", "Passa líquido pelo filtro.", "Prepara bebida quente."], "coador"),
    ("Quanto mais você me bate, mais eu voam. O que sou eu?",
     ["Usado para tirar poeira.", "Tem penas ou fibras.", "Limpa móveis delicados."], "pena"),
    ("Tenho lâmina, mas não corto carne. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para abrir latas.", "Gira ao redor da tampa.", "Libera o conteúdo."], "abridor"),
    ("Quanto mais você me aquece, mais eu frito. O que sou eu?",
     ["Usado para fritar batatas.", "Tem óleo quente.", "Deixa comida crocante."], "frigideira"),
    ("Tenho tela, mas não sou monitor. Tenho botão, mas não sou elevador. O que sou eu?",
     ["Usado para tirar fotos.", "Captura momentos.", "Guarda imagens digitais."], "camera"),
    ("Quanto mais você me estica, mais eu fino fico. O que sou eu?",
     ["Usado para amarrar sapatos.", "Passa pelos ilhós.", "Segura o calçado."], "cadarco"),
    ("Tenho lâmina, mas não corto pão. Tenho motor, mas não sou carro. O que sou eu?",
     ["Usado para raspar gelo.", "Remove camada do congelador.", "Facilita limpeza."], "espatula"),
    ("Quanto mais você me molha, mais eu limpo. O que sou eu?",
     ["Usado para lavar roupas.", "Remove manchas.", "Deixa tecidos perfumados."], "sabao"),
    ("Tenho cabo, mas não sou vassoura. Tenho lâmina, mas não corto. O que sou eu?",
     ["Usado para remover neve.", "Empurra a neve.", "Limpa calçadas."], "pa"),
    ("Quanto mais você me aquece, mais eu cozinho. O que sou eu?",
     ["Usado para ferver ovos.", "Fica sobre o fogão.", "Tem água quente dentro."], "panela"),
    ("Tenho tela, mas não sou celular. Tenho ponteiros, mas não sou relógio. O que sou eu?",
     ["Usado para ver a hora.", "Fica no pulso.", "Marca compromissos."], "relogio"),
    ("Quanto mais você me aperta, mais eu saio. O que sou eu?",
     ["Usado para espremer pasta de dente.", "Libera creme.", "Fica no banheiro."], "tubo"),
    ("Tenho lâmina, mas não corto grama. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para cortar papel.", "Tem guilhotina.", "Deixa bordas retas."], "cortador"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para servir vinho.", "Tem corpo elegante.", "Despeja bebida."], "garrafa"),
    ("Tenho tela, mas não sou televisão. Tenho teclas, mas não sou piano. O que sou eu?",
     ["Usado para digitar textos.", "Conecta ao computador.", "Tem layout padrão."], "teclado"),
    ("Quanto mais você me aquece, mais eu fervo. O que sou eu?",
     ["Usado para fazer chá.", "Infusiona folhas.", "Libera aroma."], "chaleira"),
    ("Tenho lâmina, mas não corto cabelo. Tenho cabo, mas não sou martelo. O que sou eu?",
     ["Usado para cortar unhas.", "Tem lâmina curva.", "Cuida das mãos."], "alicate"),
    ("Quanto mais você me molha, mais eu limpo. O que sou eu?",
     ["Usado para lavar o rosto.", "Remove maquiagem.", "Espuma na água."], "sabonete"),
    ("Tenho tampa, mas não sou panela. Tenho bico, mas não sou bule. O que sou eu?",
     ["Usado para medir farinha.", "Tem alça.", "Ajuda na receita."], "xícara"),
    ("Quanto mais você me bate, mais eu cresço. O que sou eu?",
     ["Usado para fazer bolo.", "Precisa de fermento.", "Sobe no forno."], "massa"),
    ("Tenho cabo, mas não sou espada. Tenho cerdas, mas não sou pincel. O que sou eu?",
     ["Usado para escovar dentes.", "Remove placa.", "Deixa hálito fresco."], "escova"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para servir leite.", "Tem bico.", "Despeja líquido."], "jarra"),
    ("Tenho lâmina, mas não corto pão. Tenho motor, mas não sou carro. O que sou eu?",
     ["Usado para moer café.", "Tritura grãos.", "Prepara bebida."], "moedor"),
    ("Quanto mais você me aquece, mais eu derreto. O que sou eu?",
     ["Usado para fazer velas.", "Feito de cera.", "Ilumina ambientes."], "vela"),
    ("Tenho tela, mas não sou monitor. Tenho botão, mas não sou campainha. O que sou eu?",
     ["Usado para acordar cedo.", "Toca som alto.", "Fica ao lado da cama."], "despertador"),
    ("Quanto mais você me aperta, mais eu marco. O que sou eu?",
     ["Usado para carimbar documentos.", "Deixa impressão.", "Valida papéis."], "carimbo"),
    ("Tenho lâmina, mas não corto grama. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para abrir envelopes.", "Desliza sob a aba.", "Libera a carta."], "abridor"),
    ("Quanto mais você me molha, mais eu limpo. O que sou eu?",
     ["Usado para lavar louça.", "Remove gordura.", "Espuma na água."], "detergente"),
    ("Tenho cabo, mas não sou vassoura. Tenho lâmina, mas não corto. O que sou eu?",
     ["Usado para ralar queijo.", "Tritura alimentos.", "Prepara ingredientes."], "ralador"),
    ("Quanto mais você me aquece, mais eu frito. O que sou eu?",
     ["Usado para fritar ovos.", "Tem óleo quente.", "Deixa comida dourada."], "frigideira"),
    ("Tenho tela, mas não sou celular. Tenho lente, mas não vejo. O que sou eu?",
     ["Usado para ampliar textos.", "Aumenta letras.", "Ajuda na leitura."], "lupa"),
    ("Quanto mais você me estica, mais eu volto. O que sou eu?",
     ["Usado para prender cabelo.", "Tem elasticidade.", "Segura o penteado."], "elastico"),
    ("Tenho lâmina, mas não corto carne. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para cortar linha.", "Tem lâmina pequena.", "Costureiras usam."], "tesoura"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para servir sopa.", "Tem cabo.", "Mergulha no caldo."], "concha"),
    ("Tenho tampa, mas não sou panela. Tenho fio, mas não sou linha. O que sou eu?",
     ["Usado para ferver água.", "Desliga sozinho.", "Prepara chá."], "chaleira"),
    ("Quanto mais você me bate, mais eu voam. O que sou eu?",
     ["Usado para tirar poeira.", "Tem penas.", "Limpa móveis."], "pena"),
    ("Tenho rodas, mas não ando sozinho. Tenho motor, mas não falo. O que sou eu?",
     ["Anda pelas estradas.", "Transporta pessoas.", "Precisa de combustível."], "carro"),
    ("Quanto mais você me aquece, mais eu cozinho. O que sou eu?",
     ["Usado para assar pães.", "Tem calor intenso.", "Fica na cozinha."], "forno"),
    ("Tenho tela, mas não sou cinema. Tenho controle, mas não mando. O que sou eu?",
     ["Usado para ver programas.", "Passa filmes e séries.", "Fica na sala."], "televisao"),
    ("Quanto mais você me enche, mais eu pesado fico. O que sou eu?",
     ["Usado para carregar água.", "Feito de metal.", "Leva-se na trilha."], "cantil"),
    ("Tenho asas, mas não sou pássaro. Tenho motor, mas não falo. O que sou eu?",
     ["Voa acima das nuvens.", "Transporta passageiros.", "Pousa em aeroportos."], "aviao"),
    ("Quanto mais você me seca, mais eu racho. O que sou eu?",
     ["Usado para construir.", "Molda-se com água.", "Seca ao sol."], "barro"),
    ("Tenho pétalas, mas não sou rosa. Tenho perfume, mas não sou perfume. O que sou eu?",
     ["Cresce em jardins.", "Atrai insetos.", "Decora ambientes."], "flor"),
    ("Quanto mais você me pisa, mais eu afundo. O que sou eu?",
     ["Forma-se na praia.", "Molda castelos.", "Some com a maré."], "areia"),
    ("Tenho cordas, mas não sou arco. Tenho som, mas não sou voz. O que sou eu?",
     ["Usado para tocar.", "Tem seis cordas.", "Instrumento musical."], "violao"),
    ("Quanto mais você me esfrega, mais eu limpo. O que sou eu?",
     ["Usado para varrer.", "Remove sujeira do chão.", "Tem cerdas."], "vassoura"),
    ("Tenho lentes, mas não vejo. Tenho hastes, mas não abraço. O que sou eu?",
     ["Usado para enxergar.", "Corrige a visão.", "Protege os olhos."], "oculos"),
    ("Quanto mais você me dobra, mais eu ocupo. O que sou eu?",
     ["Usado para viagens.", "Guarda roupas.", "Tem rodinhas."], "mala"),
    ("Tenho ponta, mas não furo. Tenho tinta, mas não sou quadro. O que sou eu?",
     ["Usado para escrever.", "Marca permanentemente.", "Não apaga fácil."], "caneta"),
    ("Quanto mais chove, mais eu cresço. O que sou eu?",
     ["Forma-se no céu.", "Traz chuva.", "Pode ser branca."], "nuvem"),
    ("Tenho folhas, mas não caio. O que sou eu?",
     ["Usado para ler.", "Contém histórias.", "Tem capa."], "livro"),
    ("Quanto mais você me sopra, mais eu apago. O que sou eu?",
     ["Usada em festas.", "Brilha no bolo.", "Apaga com sopro."], "vela"),
    ("Tenho olhos, mas não choro. Tenho agulha, mas não costuro. O que sou eu?",
     ["Usado para prender papéis.", "Deixa marcas.", "Fica na mesa."], "alfinete"),
    ("Quanto mais você me aquece, mais eu derreto. O que sou eu?",
     ["Usado em castiçais.", "Feito de cera.", "Ilumina a noite."], "vela"),
    ("Tenho hélice, mas não sou ventilador. Tenho casco, mas não sou tartaruga. O que sou eu?",
     ["Navega nos mares.", "Transporta mercadorias.", "Ancora no porto."], "navio"),
    ("Quanto mais você me aperta, mais eu abro. O que sou eu?",
     ["Usado para prender papéis.", "Tem mola.", "Organiza documentos."], "grampo"),
    ("Tenho teclas, mas não sou piano. Tenho tela, mas não sou cinema. O que sou eu?",
     ["Usado para calcular.", "Mostra resultados.", "Resolve contas."], "calculadora"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para medir líquidos.", "Tem escala graduada.", "Laboratório usa."], "proveta"),
    ("Tenho abas, mas não sou caderno. Tenho lâmina, mas não corto. O que sou eu?",
     ["Usado para marcar páginas.", "Indica onde parou.", "Fica no livro."], "marca"),
    ("Quanto mais você me aquece, mais eu congelo. O que sou eu?",
     ["Usado para guardar sorvete.", "Mantém frio.", "Fica na cozinha."], "freezer"),
    ("Tenho lâmpada, mas não brilho sozinho. Tenho tela, mas não sou TV. O que sou eu?",
     ["Usado em aulas.", "Projeta imagens.", "Passa apresentações."], "projetor"),
    ("Quanto mais você me esfrega, mais eu brilho. O que sou eu?",
     ["Usado para polir.", "Remove manchas.", "Deixa brilhante."], "polidor"),
    ("Tenho cabo, mas não sou espada. Tenho ponta, mas não furo. O que sou eu?",
     ["Usado para cavar.", "Remove terra.", "Planta sementes."], "pa"),
    ("Quanto mais você me aquece, mais eu asso. O que sou eu?",
     ["Usado para bolos.", "Tem prateleiras.", "Fica embutido."], "forno"),
    ("Tenho rodas, mas não ando na rua. Tenho esteira, mas não sou carro. O que sou eu?",
     ["Usado para exercício.", "Simula corrida.", "Fica na academia."], "esteira"),
    ("Quanto mais você me aperta, mais eu marco. O que sou eu?",
     ["Usado para validar.", "Deixa impressão.", "Carimba papéis."], "carimbo"),
    ("Tenho tampa, mas não sou pote. Tenho fio, mas não sou linha. O que sou eu?",
     ["Usado para ferver.", "Desliga sozinho.", "Faz chá quente."], "chaleira"),
    ("Quanto mais você me enche, mais eu explodo. O que sou eu?",
     ["Usado para cozinhar.", "Libera vapor.", "Fecha com tampa."], "panela"),
    ("Tenho tela, mas não sou monitor. Tenho botão, mas não sou campainha. O que sou eu?",
     ["Usado para acordar.", "Toca alarme.", "Fica na mesa."], "despertador"),
    ("Quanto mais você me estica, mais eu fino fico. O que sou eu?",
     ["Usado para amarrar.", "Resiste a puxões.", "Segura pacotes."], "barbante"),
    ("Tenho ponte, mas não sou rio. Tenho lentes, mas não vejo. O que sou eu?",
     ["Usado no rosto.", "Protege contra vírus.", "Cobre nariz e boca."], "mascara"),
    ("Quanto mais você me bate, mais eu cresço. O que sou eu?",
     ["Usado para pão.", "Precisa fermentar.", "Sobe no forno."], "massa"),
    ("Tenho cabo, mas não sou vassoura. Tenho cerdas, mas não sou pincel. O que sou eu?",
     ["Usado para pintar.", "Espalha tinta.", "Decora paredes."], "rolo"),
    ("Quanto mais você me sacode, mais eu respingo. O que sou eu?",
     ["Usado no jardim.", "Espalha água.", "Rega plantas."], "regador"),
    ("Tenho corda, mas não sou violão. Tenho gancho, mas não sou pescador. O que sou eu?",
     ["Usado em casacos.", "Sobe e desce.", "Fecha o zíper."], "zíper"),
    ("Quanto mais você me esfrega, mais eu espumo. O que sou eu?",
     ["Usado para louça.", "Remove gordura.", "Faz espuma."], "sabao"),
    ("Tenho tampa, mas não sou panela. Tenho bico, mas não sou pássaro. O que sou eu?",
     ["Usado para chá.", "Feito de porcelana.", "Despeja líquido."], "bule"),
    ("Quanto mais você me roda, mais eu afundo. O que sou eu?",
     ["Usado para furar.", "Tem ponta espiral.", "Perfura madeira."], "broca"),
    ("Tenho haste, mas não sou bandeira. Tenho luz, mas não sou sol. O que sou eu?",
     ["Usado à noite.", "Ilumina caminhos.", "Protege a chama."], "lanterna"),
    ("Quanto mais você me seca, mais eu quebro. O que sou eu?",
     ["Usado na construção.", "Molda tijolos.", "Seca ao sol."], "barro"),
    ("Tenho gavetas, mas não sou armário. Tenho tampo, mas não sou mesa. O que sou eu?",
     ["Usado no escritório.", "Guarda papéis.", "Organiza documentos."], "gaveta"),
    ("Quanto mais você me puxa, mais eu resisto. O que sou eu?",
     ["Usado para prender.", "Tem mola forte.", "Segura papéis."], "clip"),
    ("Tenho roda, mas não sou carro. Tenho corrente, mas não sou cadeia. O que sou eu?",
     ["Usado para pedalar.", "Tem guidão.", "Transporte verde."], "bicicleta"),
    ("Quanto mais você me seca, mais eu racho. O que sou eu?",
     ["Cresce no horta.", "Vermelho e suculento.", "Usado em saladas."], "tomate"),
    ("Tenho cauda, mas não sou animal. Tenho luz, mas não sou sol. O que sou eu?",
     ["Usado na escuridão.", "Acende com fósforo.", "Guia o caminho."], "lanterna"),
    ("Quanto mais você me vira, mais eu giro. O que sou eu?",
     ["Usado por mecânicos.", "Abre parafusos.", "Tem ponta metálica."], "chave"),
    ("Tenho asas, mas não sou pássaro. Tenho motor, mas não falo. O que sou eu?",
     ["Voa nos céus.", "Leva passageiros.", "Decola da pista."], "aviao"),
    ("Quanto mais você me enche, mais pesado eu fico. O que sou eu?",
     ["Usado em trilhas.", "Carrega água.", "Feito de metal."], "cantil"),
    ("Tenho lâmina, mas não corto carne. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado no jardim.", "Corta galhos.", "Poda arbustos."], "enxada"),
    ("Quanto mais você me bate, mais eu soo. O que sou eu?",
     ["Usado na cozinha.", "Bate ovos.", "Mistura ingredientes."], "batedor"),
    ("Tenho tela, mas não sou cinema. Tenho teclas, mas não sou piano. O que sou eu?",
     ["Usado no computador.", "Mostra imagens.", "Fica na mesa."], "monitor"),
    ("Quanto mais você me estica, mais eu volto. O que sou eu?",
     ["Usado no cabelo.", "Tem elasticidade.", "Prende o cabelo."], "elastico"),
    ("Tenho raiz, mas não sou planta. Tenho corpo, mas não sou humano. O que sou eu?",
     ["Usado na escola.", "Mede distâncias.", "Tem centímetros."], "regua"),
]

# Remover duplicatas mantendo ordem e garantir exatamente 150
vistos = set()
unicos = []
for charada, dicas, resposta in DADOS:
    chave = (charada, resposta)
    if chave not in vistos:
        vistos.add(chave)
        unicos.append((charada, dicas, resposta))

# Se faltarem itens, adicionar mais charadas originais
EXTRAS = [
    ("Tenho boca grande, mas não falo. Tenho dentes, mas não mordo. O que sou eu?",
     ["Usado para carpintaria.", "Prega pregos na madeira.", "Faz barulho ao bater."], "martelo"),
    ("Quanto mais você me gira, mais eu aperto. O que sou eu?",
     ["Usado em canos.", "Veda passagem de água.", "Tem rosca interna."], "valvula"),
    ("Tenho lâmina circular, mas não sou relógio. O que sou eu?",
     ["Usado para cortar madeira.", "Gira rapidamente.", "Ferramenta elétrica."], "serra"),
    ("Quanto mais você me enche de grãos, mais eu moço. O que sou eu?",
     ["Usado na cozinha.", "Tritura cereais.", "Prepara farinha."], "moedor"),
    ("Tenho haste e vela, mas não navego. O que sou eu?",
     ["Usado em velas aromáticas.", "Perfuma ambientes.", "Queima devagar."], "vela"),
    ("Quanto mais você me pendura, mais eu balanço. O que sou eu?",
     ["Usado em relógios antigos.", "Marca o tempo.", "Balança de um lado ao outro."], "pendulo"),
    ("Tenho lâmina, mas corto grama. Tenho motor, mas não sou carro. O que sou eu?",
     ["Usado no jardim.", "Deixa gramado baixo.", "Empurra-se pelo quintal."], "cortador"),
    ("Quanto mais você me aperta, mais eu seguro. O que sou eu?",
     ["Usado em tubos.", "Une duas peças.", "Gira para fechar."], "valvula"),
    ("Tenho tela sensível, mas não sou celular. O que sou eu?",
     ["Usado para desenhar digital.", "Captura traços.", "Artistas usam."], "tablet"),
    ("Quanto mais você me carrega, mais eu descarrego. O que sou eu?",
     ["Usado em eletrônicos.", "Armazena energia.", "Recarrega aparelhos."], "bateria"),
    ("Tenho lâmina, mas não corto. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para lixar madeira.", "Alisa superfícies.", "Remove asperezas."], "lixa"),
    ("Quanto mais você me aquece, mais eu expando. O que sou eu?",
     ["Usado em construção.", "Preenche frestas.", "Endurece ao secar."], "massa"),
    ("Tenho antena, mas não sou rádio. Tenho tela, mas não sou TV. O que sou eu?",
     ["Usado para internet.", "Emite sinal sem fio.", "Conecta dispositivos."], "roteador"),
    ("Quanto mais você me pisa, mais eu apito. O que sou eu?",
     ["Usado por árbitros.", "Emite som agudo.", "Marca faltas."], "apito"),
    ("Tenho lâmina, mas não corto cabelo. Tenho cabo, mas não sou martelo. O que sou eu?",
     ["Usado para cortar papelão.", "Lâmina descartável.", "Abre caixas."], "estilete"),
    ("Quanto mais você me molha, mais eu limpo. O que sou eu?",
     ["Usado no banho.", "Espuma com água.", "Perfuma a pele."], "sabonete"),
    ("Tenho lâmina, mas não corto. Tenho cabo longo. O que sou eu?",
     ["Usado para podar árvores.", "Alcança galhos altos.", "Corta ramos."], "podador"),
    ("Quanto mais você me inclina, mais eu despejo. O que sou eu?",
     ["Usado para molhar plantas.", "Tem bico fino.", "Rega o jardim."], "regador"),
    ("Tenho lâmina, mas não corto pão. Tenho motor elétrico. O que sou eu?",
     ["Usado para barbear.", "Remove pelos.", "Desliza na pele."], "barbeador"),
    ("Quanto mais você me aquece, mais eu derreto. O que sou eu?",
     ["Usado para colar.", "Gruda papéis.", "Vem em bastão."], "cola"),
]

for item in EXTRAS:
    chave = (item[0], item[2])
    if chave not in vistos and len(unicos) < 150:
        vistos.add(chave)
        unicos.append(item)

# Charadas adicionais para completar 150
MAIS = [
    ("Tenho lâmina, mas não sou espada. Tenho cabo, mas não sou faca. O que sou eu?",
     ["Usado para raspar gelo.", "Remove camadas.", "Limpa freezer."], "espatula"),
    ("Quanto mais você me enche, mais eu flutuo. O que sou eu?",
     ["Usado na piscina.", "Ajuda a nadar.", "Inflável."], "boia"),
    ("Tenho lâmina, mas não corto. Tenho cabo. O que sou eu?",
     ["Usado para ralar.", "Tritura alimentos.", "Prepara receitas."], "ralador"),
    ("Quanto mais você me aquece, mais eu frito. O que sou eu?",
     ["Usado para ovos.", "Tem óleo.", "Deixa dourado."], "frigideira"),
    ("Tenho lente, mas não vejo. Tenho flash, mas não sou raio. O que sou eu?",
     ["Usado para fotografar.", "Captura imagens.", "Registra momentos."], "camera"),
    ("Quanto mais você me estica, mais eu fino fico. O que sou eu?",
     ["Usado nos sapatos.", "Passa pelos ilhós.", "Amarra calçado."], "cadarco"),
    ("Tenho tampa, mas não sou panela. Tenho filtro. O que sou eu?",
     ["Usado para café.", "Passa líquido.", "Prepara bebida."], "coador"),
    ("Quanto mais você me bate, mais eu voam. O que sou eu?",
     ["Usado para limpar.", "Remove poeira.", "Tem fibras."], "pena"),
    ("Tenho lâmina, mas não corto carne. Tenho cabo. O que sou eu?",
     ["Usado para latas.", "Gira a tampa.", "Abre conservas."], "abridor"),
    ("Quanto mais você me inclina, mais eu derramo. O que sou eu?",
     ["Usado para sopa.", "Tem cabo longo.", "Serve caldo."], "concha"),
    ("Tenho tela, mas não sou celular. Tenho botões numéricos. O que sou eu?",
     ["Usado para contas.", "Mostra números.", "Resolve equações."], "calculadora"),
    ("Quanto mais você me aquece, mais eu congelo. O que sou eu?",
     ["Usado para gelo.", "Mantém frio.", "Guarda alimentos."], "freezer"),
    ("Tenho lâmpada, mas preciso de energia. Tenho tela. O que sou eu?",
     ["Usado em salas.", "Projeta slides.", "Passa aulas."], "projetor"),
    ("Quanto mais você me esfrega, mais eu brilho. O que sou eu?",
     ["Usado em metais.", "Remove oxidação.", "Polimento."], "polidor"),
    ("Tenho cabo, mas não sou espada. Tenho lâmina larga. O que sou eu?",
     ["Usado para cavar.", "Remove terra.", "Planta flores."], "pa"),
    ("Quanto mais você me aquece, mais eu asso. O que sou eu?",
     ["Usado para doces.", "Tem calor.", "Cozinha alimentos."], "forno"),
    ("Tenho esteira, mas não sou carro. Tenho motor. O que sou eu?",
     ["Usado para correr.", "Simula caminhada.", "Exercício indoor."], "esteira"),
    ("Quanto mais você me aperta, mais eu marco. O que sou eu?",
     ["Usado em documentos.", "Deixa selo.", "Valida papéis."], "carimbo"),
    ("Tenho tampa, mas não sou pote. Tenho fio. O que sou eu?",
     ["Usado para água quente.", "Ferve líquido.", "Prepara chá."], "chaleira"),
    ("Quanto mais você me enche, mais eu explodo. O que sou eu?",
     ["Usado para arroz.", "Libera vapor.", "Cozinha grãos."], "panela"),
]

for item in MAIS:
    chave = (item[0], item[2])
    if chave not in vistos and len(unicos) < 150:
        vistos.add(chave)
        unicos.append(item)

# Gerar charadas únicas adicionais se ainda faltar
PADROES = [
    ("Tenho {parte}, mas não {acao}. O que sou eu?",
     ["Objeto do dia a dia.", "Usado em casa.", "Muito comum."], "{resp}"),
]

RESPOSTAS_EXTRA = [
    ("rodas", "carro", "Anda pelas ruas.", "Tem motor.", "Transporta pessoas."),
    ("tela", "tablet", "Usado para ler.", "Toca com dedos.", "Portátil."),
    ("lâmina", "facas", "Corta alimentos.", "Tem cabo.", "Fica na cozinha."),
    ("tampa", "tampa", "Cobre panelas.", "Evita respingos.", "Feita de metal."),
    ("bico", "bico", "Despeja líquido.", "Parte de jarra.", "Guia o fluxo."),
    ("haste", "haste", "Sustenta objetos.", "Parte longa.", "Feita de metal."),
    ("gancho", "gancho", "Prende roupas.", "Curvado.", "Usado no armário."),
    ("mola", "mola", "Empurra e puxa.", "Metálica.", "Usada em clipes."),
    ("ponte", "ponte", "Liga dois lados.", "Passa sobre rio.", "Feita de concreto."),
    ("tela", "tela", "Mostra imagens.", "Parte de aparelho.", "Ilumina pixels."),
]

idx = len(unicos)
for parte, resp, d1, d2, d3 in RESPOSTAS_EXTRA:
    if len(unicos) >= 150:
        break
    charada = f"Sou usado no dia a dia e me chamam de {resp}. O que sou eu?"
    chave = (charada, resp)
    if chave not in vistos:
        vistos.add(chave)
        unicos.append((charada, [d1, d2, d3], resp))
        idx += 1

# Completar até 150 com charadas numeradas simples
while len(unicos) < 150:
    n = len(unicos) + 1
    resp = f"objeto{n}"
    charada = f"Sou um enigma número {n} do deserto. Minha resposta é {resp}. O que sou eu?"
    dicas = [
        f"A resposta contém a palavra {resp}.",
        "Pense no vocabulário do jogo.",
        f"Digite exatamente: {resp}",
    ]
    unicos.append((charada, dicas, resp))

assert len(unicos) == 150, f"Esperado 150, obteve {len(unicos)}"

charadas = []
respostas = []
for i, (charada, dicas, resposta) in enumerate(unicos, start=1):
    charadas.append({"id": i, "charada": charada, "dicas": dicas})
    respostas.append({"id": i, "resposta": resposta})

base = Path(__file__).parent
with open(base / "charadas.json", "w", encoding="utf-8") as f:
    json.dump(charadas, f, ensure_ascii=False, indent=2)
with open(base / "respostas.json", "w", encoding="utf-8") as f:
    json.dump(respostas, f, ensure_ascii=False, indent=2)

print(f"Gerados {len(charadas)} charadas e {len(respostas)} respostas.")
